### ISSUE TITLE
Can we add a security captcha function like recaptcha before sending SMS verification code?

### ISSUE THREAD

**Issue by AEXDragon** [cooperlyt/keycloak-phone-provider#35]
Your project is truly amazing! This additional layer of security can help prevent automated bots or malicious programs from attempting to abuse the SMS verification system. By requiring users to complete a captcha before sending the SMS verification code, it can help ensure that the verification code is only being sent to legitimate users. At the same time, it can prevent illegal users from repeatedly requesting SMS verification codes, causing financial losses.

对于国内像VAPTCHA、极验、腾讯云验证码之类的也不错。
另外我验证了阿里云短信验证码模块在Keycloak 21上正常运行。

**Comment by cooperlyt** [comment]
keycloak 自带人机验证功能，可以在流上加入即可，但他使用的Google recaptcha，没梯子在中国大陆不可用，而你说的这些国内的人机验证，应该以spi方式加入进keycloak,但这个功能和发送短信的SPI无关,应该另外再写人一库来使用keycloak支持不同的人机验证功能

**Comment by AEXDragon** [comment]
> keycloak 自带人机验证功能，可以在流上加入即可，但他使用的Google recaptcha，没梯子在中国大陆不可用，而你说的这些国内的人机验证，应该以spi方式加入进keycloak,但这个功能和发送短信的SPI无关,应该另外再写人一库来使用keycloak支持不同的人机验证功能

我知道他自带，但是似乎没法在我**发送短信之前**进行验证。参考一些国内的站点，都是发送前验证，而不是发送后提交登录、注册时再验证。

**Comment by cooperlyt** [comment]
I checked the code of KeyCloak Recaptcha, I found that it only used to registered flow. You can still use it in the registration Flow of the phone (Create a Sub flow). If you really need recaptcha, then you should use a reverse proxy(e.g. nginx), Cloudflare just work like this.  
Because recaptcha is not about phone, even not about authentication, Adding it will increase the coupling and complexity of the system

**Comment by GLY-JeffreyTCK** [comment]
@cooperlyt @AEXDragon  any solution for implement recaptcha before sending sms otp? Kindly advise
